WITH RANK_TABLE AS(SELECT USER_ID, PRODUCT_ID,DENSE_RANK() OVER(PARTITION BY USER_ID, PRODUCT_ID ORDER BY SALES_DATE) AS RANK_NUM FROM ONLINE_SALE ORDER BY USER_ID)


SELECT DISTINCT USER_ID, PRODUCT_ID FROM RANK_TABLE WHERE RANK_NUM>1
ORDER BY USER_ID ASC, PRODUCT_ID DESC