SELECT A.PRODUCT_CODE, B.SUM*A.PRICE AS SALES
FROM PRODUCT A JOIN
(SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SUM FROM OFFLINE_SALE GROUP BY PRODUCT_ID) AS B
ON A.PRODUCT_ID=B.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE