-- 코드를 작성해주세요

# 세대별 자식이 없는 수

WITH RECURSIVE tmp as (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT A.ID, A.PARENT_ID, tmp.GENERATION+1
    FROM tmp join ECOLI_DATA A
    on A.PARENT_ID=tmp.ID 
)

SELECT COUNT(*) AS COUNT, GENERATION FROM TMP WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM TMP WHERE PARENT_ID IS NOT NULL) GROUP BY GENERATION