-- 코드를 작성해주세요

SELECT QUARTER,COUNT(*) AS ECOLI_COUNT
FROM (select 
    case QUARTER(DIFFERENTIATION_DATE) 
        WHEN 1 THEN '1Q' 
        WHEN 2 THEN '2Q'
        WHEN 3 THEN '3Q'
        WHEN 4 THEN '4Q'
        ELSE '몰라' 
    END AS QUARTER
FROM ECOLI_DATA ) AS ECOLI_QUARTER
GROUP BY QUARTER
ORDER BY QUARTER