-- 코드를 입력하세요
# 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 
# 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문을 작성해주세요. 
# 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬해주세요.


WITH FIRST AS(
SELECT HISTORY_ID, DATEDIFF(END_DATE,START_DATE)+1 AS DAY, (DATEDIFF(END_DATE,START_DATE)+1)*B.DAILY_FEE AS FEE 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID=B.CAR_ID AND B.CAR_TYPE='트럭'
)

SELECT A.HISTORY_ID, ROUND(A.FEE*(1-COALESCE(B.DISCOUNT_RATE,0)*0.01)) AS FEE FROM FIRST A LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON B.CAR_TYPE='트럭' AND 
(
    (A.DAY>=90 AND B.DURATION_TYPE='90일 이상') OR
    (A.DAY<90 AND A.DAY>=30 AND B.DURATION_TYPE='30일 이상') OR
    (A.DAY<30 AND A.DAY>=7 AND B.DURATION_TYPE='7일 이상') 
)
ORDER BY FEE DESC, HISTORY_ID DESC