-- 코드를 입력하세요
WITH RankedMembers AS(
    SELECT MEMBER_ID, DENSE_RANK() OVER (ORDER BY COUNT(MEMBER_ID) DESC) AS RANK_NUM FROM REST_REVIEW GROUP BY MEMBER_ID 
)


SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B
ON A.MEMBER_ID=B.MEMBER_ID
WHERE B.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM RankedMembers
    WHERE RANK_NUM=1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT