WITH RANK_TABLE AS (SELECT ID, FISH_TYPE, LENGTH, 
DENSE_RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RANK_NUM
FROM FISH_INFO)

SELECT B.ID, A.FISH_NAME, B.LENGTH
FROM FISH_NAME_INFO A 
JOIN RANK_TABLE B
ON A.FISH_TYPE=B.FISH_TYPE
WHERE B.RANK_NUM=1
ORDER BY ID